feat: add migration to create getUserBalance

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,4 +1,9 @@
+# .husky/commit-msg
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
 .git/hooks/commit-msg $1
+if [ $? -ne 0 ]; then
+    echo "Commit message validation failed."
+    exit 1
+fi
